#!/bin/sh

sudo apt-get update && sudo apt-get -y upgrade
sudo apt-get install -y git python3 python3-pip python-dev python3-dev curl wget zsh vim tmux guake plank
mkdir -p ~/.vim/autoload ~/.vim/bundle && \
git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
sh -c "$(wget https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh -O -)"
chsh -s $(which zsh)