#!/bin/sh

sudo apt-get update && sudo apt-get -y upgrade
sudo apt-get install -y git python3 python3-pip python-dev python3-dev curl wget zsh vim tmux guake plank fonts-firacode
mkdir -p ~/.vim/autoload ~/.vim/bundle && \
git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
wget https://github.com/robbyrussell/oh-my-zsh/raw/master/tools/install.sh -O - | zsh
chsh -s $(which zsh)

cp -f .oh-my-zsh ~/.oh-my-zsh
rm -rf /root/.oh-my-zsh
ln -s $HOME/.oh-my-zsh /root/.oh-my-zsh

cp -f .zshrc ~/.zshrc
rm -f /root/.zshrc
ln -s $HOME/.zshrc /root/.zshrc

cp -f .tmux.conf ~/.tmux.conf
rm -f /root/.tmux.conf
ln -s $HOME/.tmux.conf /root/.tmux.conf

cp -f .vimrc ~/.vimrc
rm -f /root/.vimrc
ln -s $HOME/.vimrc /root/.vimrc

