#!/bin/bash

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get install -y git
sudo apt-get install -y python3
sudo apt-get install -y python3 pip
sudo apt-get install -y ctag
sudo apt-get install -y build-essential
sudo apt-get install -y python-dev
sudo apt-get install -y python3-dev
sudo apt-get install -y ycmd
sudo apt-get install -y curl
sudo apt-get install -y cmake
sudo apt-get install -y fonts-powerline
sudo apt-get install -y zsh
sudo apt-get install -y vim
sudo apt-get install -y tmux
mkdir -p ~/.vim/autoload ~/.vim/bundle && \
curl -LSso ~/.vim/autoload/pathogen.vim https://tpo.pe/pathogen.vim
cd ~/.vim
git clone https://github.com/jnurmine/Zenburn.git
cp -r Zenburn/colors ~/.vim && rm -rf Zenburn
cd ~/.vim/bundle/
git clone https://github.com/vim-airline/vim-airline.git
cd ~/.vim/bundle/
git clone https://github.com/vim-airline/vim-airline-themes
cd ~/.vim/bundle
git clone https://github.com/kien/ctrlp.vim.git
cd ~/.vim/bundle
git clone https://github.com/mattn/emmet-vim.git
cd ~/.vim/bundle
git clone https://github.com/w0rp/ale.git
cd ~/.vim/bundle
git clone https://github.com/majutsushi/tagbar.git
cd ~/.vim/bundle
git clone https://github.com/Valloric/YouCompleteMe.git
cd ~/.vim/bundle/YouCompleteMe
git submodule update --init --recursive
python3 install.py --clang-completer
sh -c "$(wget https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh -O -)"
chsh -s $(which zsh)
